# Generated by Django 2.0.1 on 2018-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
